# Generated by Django 3.2.4 on 2021-07-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Htmldata',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=70)),
                ('image', models.ImageField(default='', upload_to='media/images')),
                ('html_code', models.CharField(default='', max_length=999999999)),
                ('css_code', models.CharField(default='', max_length=999999999)),
                ('js_code', models.CharField(default='', max_length=999999999)),
            ],
        ),
    ]
