# Generated by Django 3.2.4 on 2021-07-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210702_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pythondata',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=70)),
                ('subtitle', models.TextField(max_length=150)),
                ('desc', models.TextField(max_length=99999)),
                ('image', models.ImageField(default='', upload_to='media/images')),
                ('code', models.TextField(default='', max_length=999999999)),
            ],
        ),
    ]
